@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Prijavljeni uporabnik" AS U1 <<actor>>

participant "Ogled novice" as R6 <<boundary>>
participant "Urejanje novice" as R5 <<boundary>>
participant "NovicaKontroler" as R2 <<control>>
participant "Novica" as R4 <<entity>>

activate U1
U1 -> R6: p1 := prikaziNovico()
R6 --> U1: // Prikaz novice
R6 -> R5: p2 := urediNovico()
activate R5
R5 -> R2: p3 := posodobiNovico(podatki)
activate R2
R2 -> R4: p4 := preveriPodatke(podatki)
R4 --> R2: // StatusCode
R2 --> R5: // StatusCode
deactivate R2
R5 --> U1: // Prikaži obvestilo o neuspešno urejanje \n novico zaradi neustrezni podatki
@enduml
