@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Prijavljen uporabnik" as U1 <<actor>>

participant "Ogled predloga" as R6 <<boundary>>
participant "Urejanje predloga" as R5 <<boundary>>
participant "PredlogKontroler" as R2 <<control>>
participant "Predlog" as R4 <<entity>>

activate U1
U1 -> R6: prikaziPredlog()
R6 --> U1: // Prikaz predloga
R6 -> R5: urediPredlog()
activate R5
R5 -> R2: urediPredlog(podatki)
activate R2
R2 -> R4: preveriPodatke(podatki)
R4 --> R2: //StatusCode
R2 -> R4: posodobiPredlog(podatki)
R4 --> R2: //StatusCode
R2 --> R5: //StatusCode
deactivate R2
R5 --> U1: //Prikaži obvestilo o uspešno posodobljenom predlogu
@enduml
