@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Neregistriran uporabnik" as U1 <<actor>>

participant "Iskanje" as R6 <<boundary>>
participant "Novica kontroler" as R3 <<control>> 
participant "Predlog kontroler" as R2 <<control>>
participant "Novica" as R5 <<entity>>
participant "Predlog" as R4 <<entity>>

activate U1
U1 -> R6: iskanje()
activate R6
R6 -> R3: izvediIskanje(iskalnaBeseda)
activate R3
R6 -> R2: izvediIskanje(iskalnaBeseda)
activate R2
R3 -> R5: izvediIskanje(iskalnaBeseda)
R5 --> R3: //posreduj novice
R2 -> R4: izvediIskanje(iskalnaBeseda)
R4 --> R2: //posreduj predloge
R3 --> R6: //posreduj novice
deactivate R3
R2 --> R6: //posreduj predloge
deactivate R2
R6 --> U1: //Prikaži poizvedbo novic in predlogov
@enduml
