@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Prijavljen uporabnik" as U1 <<actor>>

participant "Izbor lokacije" as R5 <<boundary>>
participant "Zemljevid kontroler" as R2 <<control>>
participant "Dostop do API-ja" as R6 <<boundary>>
participant "Google Maps" as R4 <<external API>>
participant "Novica" as R7 <<entity>>
participant "Predlog" as R8 <<entity>>


activate U1
U1 -> R5: prikazZemljevida()
activate R5
R5 -> R2: vrniZemljevid(objavaId)
R2 -> R6: dostopDoLokacije()
activate R2
R6 -> R4: pridobiZemljevid(lokacija)
R4 --> R6: //vrni Zemljevid
R6 --> R2: //StatusCode
R2 --> R5: //vrni Zemljevid
R5 --> U1: //prikazi Zemljevid s trenutno lokacijo
U1 -> R5: //Izbira lokacije na zemljevidu
R5 -> R2: izborLokacije()
R2 --> R5: vrniLokacijo()
deactivate R2
R5 -> R7: //Shrani lokacijo v novico
R5 -> R8: //Shrani lokacijo v predlog
@enduml
