@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Administrator" AS U1 <<actor>>

participant "Brisanje Novice" as R5 <<boundary>>
participant "KontrolerNovic" as R2 <<control>>
participant "Novica" as R4 <<entity>>

activate U1
U1 -> R5: p1 := izbrisiNovico()
activate R5
R5 -> R2: p2 := izbrisiNovico(novicaId)
activate R2
R2 -> R4: p5 := izbrisiNovico(novicaId)
R4 --> R2: // StatusCode
R2 --> R5: // StatusCode
deactivate R2
R5 --> U1: // Prikaži obvestilo o uspešno brisanje
@enduml

https://teaching.lavbic.net/plantuml/png/bP71Ji9048RlVOe9NlH020rD344I89eOZI6W3x1j1nWfEtLt2-ZR-2BUU2-dMo95Y8c7Dcdd-_xvkrrGYZ1ZTZ5lWy0kIUVAg1N4AbdE3HSwJJXZ0yueRMM4sjMe56UgoDmpRjqWexbUoHWIkQ6fKIfnR8PiKZGZ7nPdadu2_6oieCs27DOXOtXpthVuLg1Ey95cSccixxg8xeRNjwCpz5WPHmdbIhl_2sVB1lv3e358LwJ9ofd9OmC6KtXfGw_df_r-4EI786WC3LcbNn6UU4q9Da1Pc4I2nsMyCkzY70aFh9tX38qNAZuKFgdU_yOzfIgi8vZy7N9bQDcMrigXj0kaOBClUxkGjw5x0_GHIo_oCbzU7TX954YxaWs53KzPxVVTftKd3AHXwNJ4YVvof69p7zvgmTGfLzWHf-W3zWsF1oaUxOayzjBssDZGKks-23XUetMKCJ0KDiVTfsQ8zoV_3G00