@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Administrator" AS U1 <<actor>>

participant "Ureditev profila" as R5 <<boundary>>
participant "Uporabniki kontroler" as R2 <<control>>
participant "Uporabnik" as R4 <<entity>>

activate U1
U1 -> R5: p1 := izbrisi()
activate R5
R5 -> R2: p2 := brisanjeProfila(uporabnikId)
activate R2
R2 -> R4: p5 := izbrisiUporabnik(uporabnikId)
R4 --> R2: // StatusCode
R2 --> R5: // StatusCode
deactivate R2
R5 --> U1: // Prikaži obvestilo o uspešno brisanje profila
@enduml

https://teaching.lavbic.net/plantuml/png/bP71Ji9048RlVOe9NlH038GcnYW944rCF12G1zXs1nrRTkhi5j6tyKMy-LvEMu4IyU2XJThvld_-RP_88YoPGyARAF8PkSA8MK5YqknHk7GsvPm5WXZdTOGkj2YBIrFcuG4tOPJJerlf65AzeRGeamQMCOj5cTHXIQxflu3TnWPwVQA0RKY4Nu_x7bzAT2dUqr8lX-rT9_7j-E9cSeIU6WcKKc5S-Bzmj6nK7mGw8xiYHrw_cJvsO3I7HG-khkhfS1X5nJu8EWj1g_8Q2k4bvQO3niCiLZwfyesygN9e52mcSPGHPEo2S8xIM7srqkRLdr933fJK_qIXIgzwqze4r9wHLkqEjS0b53sul0PwJuGydPxjgLaSQS6AwYlLhwYACUuPfyqXJiljkZlR5lkHTgp4WOfnAtvNxz3KdjsVFUVdC0ycb7x25kkOdvg70ui7s-8QM_HgR2gKcQzF0axMw0Fb30obB_3hm_7k2DiVyGq0