@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Prijavljeni uporabnik" AS U1 <<actor>>

participant "Objava novice" as R5 <<boundary>>
participant "KontrolerNovic" as R2 <<control>>
participant "Novica" as R4 <<entity>>

activate U1
U1 -> R5: p1 := objaviNovico()
activate R5
R5 -> R2: p2 := dodajNovico(podatki)
activate R2
R2 -> R4: p5 := preveriPodatke(podatki)
R4 --> R2: // StatusCode
R2 -> R4: p5 := dodajNovico(podatki)
R4 --> R2: // StatusCode
R2 --> R5: // StatusCode
deactivate R2
R5 --> U1: // Prikaži obvestilo o uspešno dodajanje novico
@enduml

https://teaching.lavbic.net/plantuml/png/bP5DIiDG4CVtESLGDxeGQJ4WeWLRTADeyUC0asHgfublukGbwd6yY3llvRoas5IBu28XlFdzFrvcmHd1NCGdyXf5LSwkHCKdI33D7rLgbwLIY89NT9MDoFaUbT4SwyBVqwi_A_ZHFTaOKdkHzYXClUX4D2ETjcP9OUw_WE_43dfPiAS-f2els_KLFTVaKhhYkJsE-baxySNaw7owXPwXUawvHEV_BzXQDcel0eEPyXAROacEeIv5CN6S3-3i3Xw6S7BIKkDn59LhGnZS9AP1SD9mIWF02cvZWvCGWlfc_0P-ASwh5AJNGT3n8-FJxlmdtbBOOOU6sOxO1zFGcHlqPDqYgxS_jjnZA8TmV0eIEd6hbTszDNeRHrOke2D3Hm7D9CFbYYpjs-VS5umYQnS4XoQ8Ww1KQaXvrhAqrbYz_PNpmG7SUVHrDPMCVXbiJVnJlRhRvY2ZZPPnYpqCMymMcUFd1zkFQAZoN0W8r5L9d-zEkWBebjGjJRu0