@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Prijavljeni uporabnik" AS U1 <<actor>>

participant "Objava Predloga" as R5 <<boundary>>
participant "KontrolerPredlogov" as R2 <<control>>
participant "Predlog" as R4 <<entity>>

activate U1
U1 -> R5: p1 := objaviPredlog()
activate R5
R5 -> R2: p2 := dodajPredlog(podatki)
activate R2
R2 -> R4: p5 := preveriPodatke(podatki)
R4 --> R2: // StatusCode
R2 -> R4: p5 := dodajPredlog(podatki)
R4 --> R2: // StatusCode
R2 --> R5: // StatusCode
deactivate R2
R5 --> U1: // Prikaži obvestilo o uspešno dodajanje prelog
@enduml

https://teaching.lavbic.net/plantuml/png/bP71Jjj048RlVefHk9G3GecmX12D155xeH8Hb0SOUoTXOhDZnci3ZzCNwOttwgnj6gU9Ad6m9Mk-xvz_lO_i25OY8PFN9AaBzXKgFa66UR5MQRpBfHI5eEXh6v4F8yhH2fio_AJNS5NosZ_P679xaOuep8FejQWZNNHXMMdfUy3VZJtqyiY1nf2gl1psQtfkoEVqWrVsU1hlEag_Nvz_MnoWbwY1SwxGXyyB1yictK5WibJUO5jko3CqbIXcdei9NDt3mnGkBpjgFa-IQXi8azlC78IbaYjbZHF06kvImxEu1lNDZ1tXHdnGAKa7HThUcPcJzxD_bO7ikJFZxAeunEHOdLiCP1KJQtaoj-KNK4tXuYj8hCQ3_ELuozwbYLMCxCpOMMITEDnye9LzX8B7nYonWj4uCoEDHgNKalAoOsdhMC6J8Vhq5Eu3XgPUYAEzWCCh_wiFnziTEDgfcNROmxJ3x4eBVF_DzYzQgWEN0W9DNT7xBozz0_GRYeUn5dy0