@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Prijavljeni uporabnik" AS U1 <<actor>>

participant "Objava Predloga" as R5 <<boundary>>
participant "KontrolerPredlogov" as R2 <<control>>
participant "Predlog" as R4 <<entity>>

activate U1
U1 -> R5: p1 := objaviPredlog()
activate R5
R5 -> R2: p2 := dodajPredlog(podatki)
activate R2
R2 -> R4: p5 := preveriPodatke(podatki)
R4 --> R2: // StatusCode
R2 --> R5: // StatusCode
deactivate R2
R5 --> U1: // Prikaži obvestilo o neuspešno dodajanje\n prelog zaradi neustrezne podatke
@enduml

https://teaching.lavbic.net/plantuml/png/bP71Jjj048RlVefHkBG7X19XgK8q4aHm0Oa8oetBs3i94viTTxmsbBVfY_J6Up5hkurJSk7WbQpvld_-rJwo8rY9X4nUagGks5Ue-0GPviLQfV4kbr8KWgAlRKG-Z2X7AspAy8DUmbd9Q_zaOyZj81rHc0VHSr57kkZ2ijBIFm3_DlRGyoC76aEgyhpVh-bdGpwdQrxPvscywo2zFFzsiTX3Br43vroX3vyNzfPDkel0PAcymRRSa6TeAb7CF1SJEBk3-ocSddRKV9uarJOG9ZUPEGXB9LVA6YU0DTocXcTn3UelCtQ4A_51fIGT56bxPsPEti_-LmQovuwDiwVY49DZTMuna5LChENXt9QVG3M5a-yWiHeFyfUlM_OsJQnYP6V6pYBhnE7cBrhPJoXuRCmIAnYDOpFIQ5HABIalEvQsZXKy7AAFZk0kO6ZgXJZg0eP-kmD7EtlI3hkVTfYzIO5lVzWkqr8Tk1GGyDJK5RtzzjBtHh-X1nyRMNjujTTtt451wTKJzDte7G00