@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Neregistriran uporabnik" AS U1 <<actor>>

participant "Ogled novice" as R5 <<boundary>>
participant "KontrolerNovic" as R2 <<control>>
participant "Novica" as R4 <<entity>>

activate U1
U1 -> R5: p1 := prikaziNovico()
activate R5
R5 -> R2: p2 := prikaziNovico(idNovica)
activate R2
R2 -> R4: p5 := vrniNovico(idNovica)
R4 --> R2: // Novica
R2 --> R5: // Novica
deactivate R2
R5 --> U1: // Prikaži novico
@enduml

https://teaching.lavbic.net/plantuml/png/bP71Ji9048Rl-nGJlEZ141gQ688aGFIYGOBo0DjsA9EMtJhT0lfmtdmlfriYHRXuQ0-pt_VFt-sQ4eILjIwoUwNAZ4oXMMyWqd6MigrC4jlSCZZMffGZDAv59RZILUxUSE_6EQLc8ySGomkvHUdOMPvOJf2dFYpA9VqC-DtOGBirEMn3p7PtsI_nlK8JupEjv37OtdKLFaxk7gONwBbcHp4LshZ_2nVBAlyXq9aXOqgbOv9RWwgmh2D3MGV6hx3imN3ekT58gU8O2PsNDCS4ZDrIZ1tG9In2OQDwY-OFmK_e9siSsnnvLWiD7mWVD_E_kATqW_K5avz4hWwjIzDMEvHgIjhTZcJl08eU3EwXOChq9tdPNjySsKMef5tD1i86vombpSQs4oXfM3jzSSBQsR8v5wJVxI6vsuLcwir3jUCmmPFmq2FBdaVcTPtlBsekrFu0