@startuml DPU

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam usecase {
  backgroundColor white
  borderColor #5FB8EC
  arrowColor black
}
skinparam actorBorderColor black
skinparam actorBackgroundColor white

left to right direction

actor "Neregistriran\nuporabnik" AS U1
actor "Registriran\nuporabnik" AS U2
actor "Občni\ndelavec" AS U3
actor "Predstavnik\nobčine" AS U4
actor "Administrator" AS U5

actor "Google\nMaps\nAPI" AS S1
actor "Upravna\nenota\nobčine" AS S2
' actor "Mail" AS S3

rectangle "Vaš sistem" {
  usecase "Registracija" AS PU1
  usecase "Prijava" AS PU2
  usecase "Odjava" AS PU3
  usecase "Brisanje\nprofila" AS PU6
  usecase "Dodajanje\nnovic" AS PU7
  usecase "Pregled\nnovic" AS PU10
  usecase "Dodajanje\npredlogov" AS PU11
  usecase "Pregled\npredlogov" AS PU14
  usecase "Glasovanje" AS PU12
  usecase "Komentiranje" AS PU19
  usecase "Izbira\nlokacije" AS PU19
  usecase "Ogled\nlokacije" AS PU20
}

U2 -left-|> U1

U1 -> (PU1)
U2 --> (PU2)
U2 --> (PU3)
U2 --> (PU4)
U1 --> (PU10)
U2 --> (PU10)
U2 --> (PU12)
U4 --> (PU12)
U1 --> (PU14)
U2 --> (PU14)
U2 --> (PU19)
U2 --> (PU20)

(PU6) .up.> (PU4) : extend
(PU7) .up.> (PU10) : extend
(PU11) .up.> (PU14) : extend

(PU19) -down-> S1
(PU12) -down-> S2

@enduml
