@startuml
!theme blueprint

left to right direction
skinparam linetype ortho

() Uporabniki <<interface>>
() Novice <<interface>>
() Predlogi <<interface>>

component "Spletna stran"  as SS <<subsystem>> {
   component "Avtentikacija in verifikacija" <<component>> as AV
   component "Upravljanje novic" <<component>> as UN
   component "Upravljanje predlogov" <<component>> as UP
}


() "Avtentikacija in verifikacija" <<interface>> as AVI
() "Upravljanje novic" <<interface>> as UNI
() "Upravljanje predlogov" <<interface>> as UPI
() "Glasovanje med predlogi" <<interface>> as GI
() "Zunanji API vmesnik" <<interface>> as APII
() "SQL vmesnik" <<interface>> as SQL

component Strežnik <<subsystem>> {
   component "Strežnik uporabnikov" <<component>> as SU
   component "Strežnik novic" <<component>> as SN
   component "Strežnik predlogov" <<component>> as SP
   component "Zunanji API" <<component>> as API
}

component "Podatkovni strežnik" as PS <<subsystem>> {
   component "Relacijska podatkovna baza" as DPB <<component>>
   component "Podatkovna baza" as PB2 <<component>>
}


Uporabniki --> AV
Novice --> UN
Predlogi --> UP

AV --> AVI
UN --> UNI

AVI --> SU
UNI --> SN
UPI --> SP
GI --> SP
APII --> API
UP --> UPI

SU --> SQL 
SN --> SQL
SP --> SQL
API --> SQL
SP -> PB2
SQL --> DPB
@enduml